all:
	javac -sourcepath src -classpath lib -d lib src/POOCasino.java
	javac -sourcepath src -classpath lib -d lib src/PlayerB01902039.java
run:
	java -classpath lib foop.POOCasino 1000 100 foop.PlayerB01902039 foop.PlayerB01902039 foop.PlayerB01902039 foop.PlayerB01902039
clean:
	rm -f lib/foop/POOCasino.class
	rm -f lib/foop/Computer.class
	rm -f lib/foop/RandomIndex.class
	rm -f lib/foop/PlayerB01902039.class
